 name: greet user
 # on: push
 on: workflow_dispatch
 jobs:
    greet:
      runs-on: ubuntu-latest
      steps:
      - name: greet user
        run: echo "Hello World$$$"
      - name: bye user
        run: echo "Goodbye World!!!"


